package vn.hoidanit.laptopshop.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import vn.hoidanit.laptopshop.domain.User;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {
    User save(User hoidanit);

    List<User> findAll();

    void deleteById(long id);

    User findById(long id);

    boolean existsByEmail(String email);
    
    // Find user by email - automatically generated by Spring Data JPA
    User findByEmail(String email);
}
